version: '3.7'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   PUID: 1000
    #   PGID: 1000
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"

